<?php
require_once('connections/conn.php');
include('logged_in_check.php');
include('directory_protect.php');
include('components/header/header.php');
include('components/navBar/navBar.php');

$query_managers = $conn->query("SELECT * FROM managerdir AS m JOIN divisions AS d ON (m.division_id=d.division_id) ORDER BY m.conference ASC, m.division_id ASC, m.teamname ASC");
// $change is an array holding all the manager data from a row in the database generated by a fetch call
function array_alter($change)
{
    // start manager1
    if ($change['teamname'] != '') {
        echo '<b>' . $change['teamname'] . '</b><br />';
    }
    if ($change['description1'] != '') {
        echo '<i>' . $change['description1'] . '</i><br />';
    }
    // manager1 name and address lines
    $man1a = array_slice($change, 5, 3);
    foreach ($man1a as $x) {
        if ($x != '') {
            echo $x . '<br />';
        }
    }
    // manager1 city, state and zip line
    if (($change['city1'] != '') && ($change['state1'] != '')) {
        echo $change['city1'] . ', ' . $change['state1'] . ' &nbsp;' . $change['zip1'] . '<br />';
    } elseif ($change['city1'] != '') {
        echo $change['city1'] . ' &nbsp;' . $change['zip1'] . '<br />';
    } elseif ($change['state1'] != '') {
        echo $change['state1'] . ' &nbsp;' . $change['zip1'] . '<br />';
    } elseif ($change['zip1'] != '') {
        echo $change['zip1'] . '<br />';
    }
    // manager1 country line
    if ($change['country1'] != '') {
        echo $change['country1'] . '<br />';
    }
    // manager1 phone number lines
    $man1phone = array_slice($change, 12, 2);
    foreach ($man1phone as $x) {
        if ($x != '') {
            echo $x . '<br />';
        }
    }
    // manager1 email lines
    $man1email = array_slice($change, 14, 2);
    foreach ($man1email as $x) {
        if ($x != '') {
            echo '<a href="mailto:' . $x . '">' . $x . '</a><br />';
        }
    }
    // start manager2
    if ($change['description2'] != '') {
        echo '<br /><i>' . $change['description2'] . '</i><br />';
    }
    // manager2 name and address lines
    $man2a = array_slice($change, 17, 3);
    foreach ($man2a as $y) {
        if ($y != '') {
            echo $y . '<br />';
        }
    }
    // manager2 city, state and zip line
    if (($change['city2'] != '') && ($change['state2'] != '')) {
        echo $change['city2'] . ', ' . $change['state2'] . ' &nbsp;' . $change['zip2'] . '<br />';
    } elseif ($change['city2'] != '') {
        echo $change['city2'] . ' &nbsp;' . $change['zip2'] . '<br />';
    } elseif ($change['state2'] != '') {
        echo $change['state2'] . ' &nbsp;' . $change['zip2'] . '<br />';
    } elseif ($change['zip2'] != '') {
        echo $change['zip2'] . '<br />';
    }
    // manager2 country line
    if ($change['country2'] != '') {
        echo $change['country2'] . '<br />';
    }
    // manager2 phone number lines
    $man2phone = array_slice($change, 24, 2);
    foreach ($man2phone as $y) {
        if ($y != '') {
            echo $y . '<br />';
        }
    }
    // manager2 email lines
    $man2email = array_slice($change, 26, 2);
    foreach ($man2email as $y) {
        if ($y != '') {
            echo '<a href="mailto:' . $y . '">' . $y . '</a><br />';
        }
    }
    echo '</div>';
}

echo '<h2>MANAGER DIRECTORY</h2>';
echo '<div class="d-flex justify-content-center bigger mt-4">';
echo '<div class="mx-4 w-50">';
echo '<div class="bg-secondary text-light font-weight-bolder mb-n4 p-2">American Conference</div>';
echo '';
$conference = 'AC';
$division_id = 0;
while ($results_managers = $query_managers->fetch_assoc()) {
    if ($results_managers['conference'] != $conference) {
        echo '</div>';
        echo '<div class="mx-4 w-50">';
        echo '<div class="bg-secondary text-light font-weight-bolder mb-n4 p-2">National Conference</div>';
    }
    if ($division_id != $results_managers['division_id']) {
        echo '<div class="bg-ltgray font-weight-bolder mt-5 p-2">' . $results_managers['division'] . '</div>';
        echo '<div class="pt-4 mb-4">';
    } else {
        echo '<div class="border-top border-secondary pt-4 mb-4">';
    }
    array_alter($results_managers);
    $conference = $results_managers['conference'];
    $division_id = $results_managers['division_id'];
}
$query_managers->free_result();
echo '</div>';

include('components/footer/footer.php');
